### ISSUE TITLE
style the website

### ISSUE THREAD

**Issue by Prathamdas3** [Prathamdas3/Small-Projects#13]

**Comment by DilushaHesaranga** [comment]
I would love to work on this project. can you make me as a assignee? then I can start it

**Comment by Prathamdas3** [comment]
This website is not responsive for mobile or other small screens, Would anyone be able to make it responsive? 

It uses tailwind CSS for styling with the Daisyui library

**Comment by abhishek-kumar-91** [comment]
I would like to work on this issue, Can you assign me?
